"""Added drive_folder_id column

Revision ID: 33bc869df8b9
Revises: 5a8b8d9c2690
Create Date: 2024-04-04 15:10:11.922529

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33bc869df8b9'
down_revision = '5a8b8d9c2690'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('drive_folder_id', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('drive_folder_id')

    # ### end Alembic commands ###
