"""Added device_uid column

Revision ID: 5a8b8d9c2690
Revises: 8c7bf147253e
Create Date: 2024-04-04 13:52:31.921624

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a8b8d9c2690'
down_revision = '8c7bf147253e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('device_uid', sa.String(length=30), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('device_uid')

    # ### end Alembic commands ###
